name: multi-digit
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.12
    - numpy==1.12.0
    - matplotlib==1.5.1
    - jupyter==1.0.0
    - scikit-learn==0.18.1
    - scipy==0.18.1
    - pillow 4.0.0
    - h5py==2.6.0
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
